import 'dart:io';

import 'package:visual_contract/visual_contract.dart';

/// Run from this package root. Never label this fixture as device evidence.
void main() {
  final recording = createSyntheticSceneSignalRecording();
  final output = Directory('test/fixtures/synthetic')
    ..createSync(recursive: true);
  File('${output.path}/signals.bin').writeAsBytesSync(recording.signalBytes);
  File(
    '${output.path}/timeline.json',
  ).writeAsStringSync('${recording.timelineJson}\n');
  File('${output.path}/PROVENANCE.txt').writeAsStringSync(
    'SYNTHETIC DEMONSTRATION. Generated by tool/write_synthetic_fixture.dart.\n'
    'Not captured from a microphone or a physical device.\n',
  );
}
